name: AG Mod X - Release package

on:
  push:
    paths-ignore:
      - 'website/**'
  pull_request:
    paths-ignore:
      - 'website/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2
      with:
        fetch-depth: 0

    - name: Install NodeJS
      uses: actions/setup-node@v6.4.0
      with:
        node-version: 20
    
    - name: Install node dependencies
      run: npm install
    
    - name: Build AG Mod X packages
      run: npm run build

    - name: Get current tag and commit SHA for artifact naming
      id: naming
      run: |
        if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
          tag="${GITHUB_REF_NAME}"
        else
          tag="v$(node -p \"require('./package.json').version\")"
        fi

        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload AG Mod X package
      uses: actions/upload-artifact@v7.0.1
      with:
        name: agmodx-${{ steps.naming.outputs.tag }}-dev-${{ steps.naming.outputs.sha_short }}
        path: dist/valve
